### send message inmediately several phone number remote

POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"PAGAME","status":"immediately"}}


### send schedule phone message remote each minutte
POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"PAGAME","status":"schedule", "cron":"cron(0/1 * * * ? *)"}}

### send schedule phone message start to work remote run at 8 am every monday through friday
POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"start wo work","status":"schedule", "cron":"cron(0 8 ? * MON-FRI *)"}}


### send schedule phone message time to lunch remote run at 8 am every monday through friday
POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"time to lunch","status":"schedule", "cron":"cron(0 12 ? * MON-FRI *)"}}


### send schedule phone message finish work remote run at 8 am every monday through friday
POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"finish work","status":"schedule", "cron":"cron(0 18 ? * MON-FRI *)"}}

### send email remote
POST https://6myq4zxol1.execute-api.us-east-1.amazonaws.com/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "email":"jjvergara79@misena.edu.co", "source":"jjvergara79@misena.edu.co","destination":["cibernetikov@gmail.com"],"subject":{"Data":"Test SES massive without verification", "Charset": "UTF-8"},"message":{"Text":{"Data":"prueba SES","Charset":"UTF-8"}}}}

#################################################################################-----------------------------------------------

### send message inmediately several phone number local

POST http://localhost:3000/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"PAGAME","status":"immediately"}}


### send schedule phone message local
POST http://localhost:3000/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "location_code": "+57", "timezone":"GMT+5", "phone_numbers":[3505784483], "message":"PAGAME","status":"schedule", "cron":"cron(0/1 * * * ? *)"}}


### send email local
POST http://localhost:3000/dev/create
Content-Type: application/json

{"user_id":"123456", "noti_data": { "email":"jjvergara79@misena.edu.co", "source":"jjvergara79@misena.edu.co","destination":["jeisonvergaradiaz@gmail.com"],"subject":{"Data":"Test SES massive without verification", "Charset": "UTF-8"},"message":{"Text":{"Data":"prueba SES","Charset":"UTF-8"}},"status":"awaiting"}}
